# Installs a global 'bj' PowerShell command that runs the bj.mjs CLI
# from any directory, with BJ_BASE_URL pre-set to production.
#
# After running this once: open a fresh PowerShell window and try
#   bj meta status
#   bj ai brief
#   bj outbox list
#
# Re-running this script is safe. It removes the old definition
# before appending a fresh one. Idempotent.
#
# To uninstall: edit $PROFILE manually and remove the function block
# between the # BLUEJAYS-BJ-START and # BLUEJAYS-BJ-END markers.
#
# NOTE: this file is intentionally pure ASCII. PowerShell 5.1 reads
# unmarked .ps1 files as Windows-1252 and chokes on em-dashes or
# curly quotes. Do NOT add Unicode characters to this file.

$ErrorActionPreference = "Stop"

# Resolve the bluejays repo path relative to THIS script's location
# so the install works whether you run it from PowerShell, the repo
# root, or by double-clicking.
$RepoPath = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
$BjScript = Join-Path $RepoPath "scripts\bj.mjs"

if (-not (Test-Path $BjScript)) {
    Write-Error "Could not find $BjScript. Run this script from inside the bluejays repo."
    exit 1
}

# The function definition we inject into Ben's PowerShell profile.
# Backtick escapes `$env and `$args so the install-time variables
# are NOT substituted; they evaluate at function-CALL time instead.
$FunctionBlock = @"
# BLUEJAYS-BJ-START auto-generated by scripts/install-bj-powershell.ps1
function bj {
    `$env:BJ_BASE_URL = "https://bluejayportfolio.com"
    & node "$BjScript" @args
}
# BLUEJAYS-BJ-END
"@

# Make sure the profile file exists
if (-not (Test-Path $PROFILE)) {
    New-Item -Type File -Path $PROFILE -Force | Out-Null
    Write-Host "Created PowerShell profile at $PROFILE" -ForegroundColor Yellow
}

# Strip any prior block (idempotency on re-install)
$ProfileContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
if ($null -ne $ProfileContent -and $ProfileContent -match "(?ms)# BLUEJAYS-BJ-START.*?# BLUEJAYS-BJ-END") {
    $Cleaned = [regex]::Replace(
        $ProfileContent,
        "(?ms)# BLUEJAYS-BJ-START.*?# BLUEJAYS-BJ-END\s*",
        ""
    )
    Set-Content -Path $PROFILE -Value $Cleaned -NoNewline
    Write-Host "Removed previous bj function definition" -ForegroundColor DarkGray
}

# Append the fresh block
Add-Content -Path $PROFILE -Value "`n$FunctionBlock`n"

# Hot-load into the current session so 'bj' works immediately
. $PROFILE

Write-Host ""
Write-Host "Installed. From any new PowerShell window you can now run:" -ForegroundColor Green
Write-Host "    bj meta status" -ForegroundColor Cyan
Write-Host "    bj ai brief" -ForegroundColor Cyan
Write-Host "    bj outbox list" -ForegroundColor Cyan
Write-Host "    bj meta launch wave-1" -ForegroundColor Cyan
Write-Host ""
Write-Host "Function lives in $PROFILE" -ForegroundColor DarkGray
Write-Host "Repo path baked in: $RepoPath" -ForegroundColor DarkGray
