-- Manual conversion-tracking column for client_leads.
--
-- Lets us record the revenue generated by a converted lead so the
-- dashboard can compute revenue + ROI per funnel / audience / source
-- without waiting on Shopify webhook integration. Cents (integer) to
-- avoid float rounding bugs on $/lead aggregations.
--
-- When the Shopify webhook lands later it'll populate this same column
-- automatically; manual entry handles the gap until then.

alter table public.client_leads
  add column if not exists conversion_value_cents integer;

-- Helpful index for the per-audience revenue rollup queries the
-- dashboard runs (sum over conversion_value_cents grouped by
-- audience_segment, scoped to a client). Partial — we only ever
-- aggregate non-null values.
create index if not exists client_leads_conv_value_idx
  on public.client_leads (client_slug, audience_segment)
  where conversion_value_cents is not null;
