-- Affiliate / Partner program — flat $200 per BlueJays close, manual
-- Venmo/Zelle payouts. Partners share a `?ref=<code>` link; cookie
-- captures the attribution; prospect lookup at audit submit stamps the
-- partner_code into prospects.scraped_data.partnerCode; Stripe webhook
-- creates a partner_referrals row when prospect.status flips to 'paid'.
--
-- Two tables (no Stripe Connect — payouts handled manually by Ben):
--   partners            — applicants + approved promoters
--   partner_referrals   — one row per attributed close; payout tracking
--
-- Idempotency: partner.code is unique. partner_referrals (partner_id,
-- prospect_id) is unique so the Stripe webhook can safely retry.

create extension if not exists "uuid-ossp";

-- ─── partners ────────────────────────────────────────────────────────
create table if not exists partners (
  id uuid primary key default gen_random_uuid(),
  -- Short slug used in ?ref=<code> URLs. Lowercased, alphanumeric +
  -- dashes only. Generated by the apply API as slug(name) + 4-char
  -- random suffix on collision.
  code text unique not null,
  name text not null,
  email text not null,
  phone text,
  -- Payout handle — "venmo:@bensphone" / "zelle:ben@bluejayportfolio.com"
  -- / "note: prefers cashapp $bens". Free-form so Ben can document
  -- whatever the partner gave him.
  payout_handle text,
  -- Where they plan to promote — "Facebook group X" / "my landscaping
  -- customers" / "word of mouth". Useful for approval triage.
  promotion_channel text,
  -- pending  — submitted application, awaiting Ben's manual approval
  -- approved — live partner, can attribute closes
  -- paused   — temporarily disabled (low-quality traffic, etc.)
  -- declined — application rejected
  status text not null default 'pending',
  -- Optional internal note from Ben (e.g., "neighbor's son, trust him").
  notes text,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists partners_status_idx on partners(status);
create index if not exists partners_email_idx on partners(email);

-- ─── partner_referrals ───────────────────────────────────────────────
create table if not exists partner_referrals (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references partners(id) on delete cascade,
  -- Loose FK — prospect_id is uuid in prospects table but we don't add
  -- a hard FK constraint here so a deleted prospect doesn't cascade
  -- into payout history.
  prospect_id uuid not null,
  audit_id uuid,
  -- Snapshot of the close — useful when a prospect record is later
  -- edited / deleted, the payout row stays meaningful.
  business_name text,
  closed_at timestamptz not null default now(),
  amount_cents integer not null default 20000,  -- $200 default
  -- owed — close attributed, payout pending
  -- paid — Ben sent Venmo/Zelle, recorded the date+method
  -- void — refunded close / spam attribution / duplicate
  payout_status text not null default 'owed',
  paid_at timestamptz,
  payout_method text,  -- "venmo" | "zelle" | "cashapp" | "manual"
  payout_note text,
  created_at timestamptz not null default now()
);

-- One referral per (partner, prospect) — Stripe webhook can safely
-- replay without duplicating payouts.
create unique index if not exists partner_referrals_unique
  on partner_referrals(partner_id, prospect_id);

create index if not exists partner_referrals_status_idx
  on partner_referrals(payout_status);
create index if not exists partner_referrals_partner_idx
  on partner_referrals(partner_id);
